import React, { useState, useEffect } from 'react';
import { ChevronLeft, ChevronRight, DollarSign, Download, RefreshCw, Search, FileText, X, Settings } from 'lucide-react';
import useAuthStore from '../store/authStore';
import { settingsApi } from '../utils/api';

const API = '/api';
const auth = () => ({ Authorization: `Bearer ${localStorage.getItem('hrms_token')}` });
const fmt = n => '₹' + Number(n||0).toLocaleString('en-IN', {maximumFractionDigits:0});

function PayslipModal({ slip, onClose }) {
  if (!slip) return null;
  const monthName = new Date(slip.year, slip.month-1).toLocaleString('default',{month:'long',year:'numeric'});
  const print = () => {
    const w = window.open('', '_blank');
    w.document.write(`<html><head><title>Payslip ${slip.emp_code}</title>
      <style>body{font-family:Arial;padding:40px;max-width:600px;margin:0 auto}
      h2{color:#115e59;border-bottom:2px solid #115e59;padding-bottom:8px}
      table{width:100%;border-collapse:collapse;margin:16px 0}
      td{padding:8px 12px;border-bottom:1px solid #eee;font-size:14px}
      .lbl{color:#666}.val{text-align:right;font-weight:600}
      .net{background:#f0fdf4;font-size:16px}.net .val{color:#115e59}</style></head><body>
      <h2>East Coast Hospitals Ltd — Payslip</h2>
      <p><b>${slip.emp_name}</b> (${slip.emp_code}) · ${slip.dept||''} · ${monthName}</p>
      <table>
        <tr><td class="lbl">Present Days</td><td class="val">${slip.present_days}</td></tr>
        <tr><td class="lbl">Leave Days</td><td class="val">${slip.leave_days}</td></tr>
        <tr><td class="lbl">Work Hours</td><td class="val">${slip.work_hours}</td></tr>
        <tr><td class="lbl">OT Hours</td><td class="val">${slip.ot_hours}</td></tr>
        <tr><td class="lbl">Basic Salary</td><td class="val">${fmt(slip.basic_salary)}</td></tr>
        <tr><td class="lbl">Earned (${slip.present_days} days)</td><td class="val">${fmt(slip.earned)}</td></tr>
        <tr><td class="lbl">OT Amount</td><td class="val">${fmt(slip.ot_amount)}</td></tr>
        <tr><td class="lbl">Deductions</td><td class="val">- ${fmt(slip.deductions)}</td></tr>
        <tr class="net"><td class="lbl"><b>NET PAY</b></td><td class="val">${fmt(slip.net_pay)}</td></tr>
      </table>
      <p style="color:#999;font-size:11px">Generated by EastCoast HRMS · ${new Date().toLocaleString('en-IN')}</p>
      <script>window.print()</script></body></html>`);
    w.document.close();
  };
  return (
    <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.5)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000}}>
      <div style={{background:'#fff',borderRadius:16,padding:28,width:420,boxShadow:'0 20px 60px rgba(0,0,0,0.25)'}}>
        <div style={{display:'flex',justifyContent:'space-between',marginBottom:16}}>
          <h3 style={{fontWeight:800,fontSize:17}}>Payslip — {monthName}</h3>
          <button onClick={onClose} style={{background:'none',border:'none',cursor:'pointer'}}><X size={18}/></button>
        </div>
        <div style={{background:'#f8fafc',borderRadius:10,padding:'12px 16px',marginBottom:16}}>
          <div style={{fontWeight:700}}>{slip.emp_name}</div>
          <div style={{fontSize:12,color:'#64748b'}}>{slip.emp_code} · {slip.dept||'—'}</div>
        </div>
        {[['Present Days',slip.present_days],['Leave Days',slip.leave_days],['Work Hours',slip.work_hours],['OT Hours',slip.ot_hours],
          ['Basic Salary',fmt(slip.basic_salary)],['Earned',fmt(slip.earned)],['OT Amount',fmt(slip.ot_amount)],['Deductions','- '+fmt(slip.deductions)]].map(([l,v])=>(
          <div key={l} style={{display:'flex',justifyContent:'space-between',padding:'7px 4px',borderBottom:'1px solid #f1f5f9',fontSize:13.5}}>
            <span style={{color:'#64748b'}}>{l}</span><span style={{fontWeight:600}}>{v}</span>
          </div>
        ))}
        <div style={{display:'flex',justifyContent:'space-between',padding:'12px 4px',fontSize:16,fontWeight:800,color:'#115e59'}}>
          <span>NET PAY</span><span>{fmt(slip.net_pay)}</span>
        </div>
        <button onClick={print} style={{width:'100%',height:44,borderRadius:10,border:'none',background:'#115e59',color:'#fff',fontWeight:700,cursor:'pointer',fontSize:14,display:'flex',alignItems:'center',justifyContent:'center',gap:8}}>
          <Download size={15}/> Download / Print Payslip
        </button>
      </div>
    </div>
  );
}

export default function Payroll() {
  const { user } = useAuthStore();
  const isAdmin = ['hr_admin', 'it_admin'].includes(user?.role);
  const now = new Date();
  const [month, setMonth] = useState(now.getMonth()+1);
  const [year, setYear] = useState(now.getFullYear());
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [msg, setMsg] = useState('');
  const [search, setSearch] = useState('');
  const [viewSlip, setViewSlip] = useState(null);
  const [editRow, setEditRow] = useState(null);
  const [salary, setSalary] = useState('');
  const [hra, setHra] = useState('');
  const [deductions, setDeductions] = useState('');
  
  // Settings State
  const [showSettings, setShowSettings] = useState(false);
  const [monthStartDay, setMonthStartDay] = useState(1);
  const [savingSettings, setSavingSettings] = useState(false);
  const [showReports, setShowReports] = useState(false);
  
  // Approvals State
  const [tab, setTab] = useState('payroll');
  const [approvals, setApprovals] = useState([]);

  const load = async () => {
    setLoading(true);
    try {
      const url = isAdmin
        ? `${API}/payroll/list?month=${month}&year=${year}${search?'&search='+encodeURIComponent(search):''}`
        : `${API}/payroll/my-slips`;
      const r = await fetch(url, { headers: auth() });
      const d = await r.json();
      setRows(Array.isArray(d)?d:[]);
      
      if (isAdmin) {
        const s = await settingsApi.get();
        if(s.data) setMonthStartDay(s.data.month_start_day || 1);
      }
    } catch { setRows([]); }
    setLoading(false);
  };

  const loadApprovals = async () => {
    try {
      const r = await fetch(`${API}/payroll/revisions/pending`, { headers: auth() });
      const d = await r.json();
      setApprovals(Array.isArray(d) ? d : []);
    } catch {}
  };

  useEffect(() => { 
    if (tab === 'payroll') load(); 
    if (tab === 'approvals') loadApprovals();
  }, [month, year, tab]);

  const handleApprove = async (id, action) => {
    try {
      const r = await fetch(`${API}/payroll/revisions/${id}/${action}`, { method: 'POST', headers: auth() });
      if (r.ok) { loadApprovals(); load(); }
    } catch {}
  };

  const handleGenerate = async () => {
    setGenerating(true); setMsg('');
    try {
      const r = await fetch(`${API}/payroll/generate?month=${month}&year=${year}`, { method:'POST', headers: auth() });
      const d = await r.json();
      setMsg(r.ok ? `✅ ${d.message} (${d.created} new, ${d.updated} updated)` : `❌ ${d.detail}`);
      load();
    } catch { setMsg('❌ Generate failed'); }
    setGenerating(false);
    setTimeout(()=>setMsg(''),6000);
  };

  const saveSalary = async () => {
    try {
      const r = await fetch(`${API}/payroll/${editRow.id}/salary`, {
        method:'PUT', headers:{...auth(),'Content-Type':'application/json'},
        body: JSON.stringify({ basic_salary: parseFloat(salary)||0, hra: parseFloat(hra)||0, deductions: parseFloat(deductions)||0 })
      });
      if (r.ok) { setEditRow(null); load(); }
    } catch {}
  };
  
  const saveSettings = async () => {
    setSavingSettings(true);
    try {
      await settingsApi.update({ month_start_day: monthStartDay });
      setShowSettings(false);
      load(); // Reload payrolls after settings change
    } catch (e) { alert("Failed to save settings"); }
    setSavingSettings(false);
  };

  const prevMonth = () => { if(month===1){setMonth(12);setYear(y=>y-1);} else setMonth(m=>m-1); };
  const nextMonth = () => { if(month===12){setMonth(1);setYear(y=>y+1);} else setMonth(m=>m+1); };
  const monthName = new Date(year, month-1).toLocaleString('default',{month:'long',year:'numeric'});

  const displayRows = isAdmin ? rows : rows;

  return (
    <div>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}>
        <div>
          <h1 style={{fontSize:22,fontWeight:800,color:'#0b1320'}}>Payroll</h1>
          <p style={{color:'#64748b',fontSize:14,marginTop:2}}>{isAdmin?'Generate & manage payroll from eSSL attendance':'Your payslips'}</p>
        </div>
        <div style={{display:'flex',alignItems:'center',gap:10}}>
          {isAdmin && <>
            {msg && <span style={{fontSize:12,fontWeight:600,color:msg.startsWith('✅')?'#16a34a':'#dc2626',maxWidth:280}}>{msg}</span>}
            
            <div style={{position:'relative'}}>
              <button onClick={() => setShowReports(!showReports)} style={{display:'flex',alignItems:'center',gap:6,padding:'9px 16px',borderRadius:9,border:'1px solid #e6e9ef',background:'#fff',color:'#4b5566',cursor:'pointer',fontSize:13,fontWeight:700}}>
                <Download size={14} /> Reports
              </button>
              {showReports && (
                <div style={{position:'absolute',top:'100%',right:0,marginTop:6,background:'#fff',border:'1px solid #e6e9ef',borderRadius:8,boxShadow:'0 10px 25px rgba(0,0,0,0.1)',width:180,zIndex:100}}>
                  {['Monthly Report','PT Report','ESIC Report','PF Report','Bank Transfer'].map(type => (
                    <a key={type} href={`/api/payroll/reports/${type.split(' ')[0].toLowerCase()}?month=${month}&year=${year}&token=${localStorage.getItem('hrms_token')}`} target="_blank" rel="noreferrer" style={{display:'block',padding:'10px 16px',color:'#0b1320',fontSize:13,textDecoration:'none',borderBottom:'1px solid #f1f5f9'}} onClick={()=>setShowReports(false)}>
                      {type}
                    </a>
                  ))}
                </div>
              )}
            </div>

            <button onClick={() => setShowSettings(true)} style={{display:'flex',alignItems:'center',gap:6,padding:'9px 16px',borderRadius:9,border:'1px solid #e6e9ef',background:'#fff',color:'#4b5566',cursor:'pointer',fontSize:13,fontWeight:700}}>
              <Settings size={14} /> Settings
            </button>
            <button onClick={handleGenerate} disabled={generating} style={{display:'flex',alignItems:'center',gap:6,padding:'9px 16px',borderRadius:9,border:'none',background:generating?'#9fb7b4':'#115e59',color:'#fff',cursor:generating?'not-allowed':'pointer',fontSize:13,fontWeight:700}}>
              <RefreshCw size={14} style={{animation:generating?'spin 1s linear infinite':'none'}}/> {generating?'Generating...':'Generate Payroll'}
            </button>
          </>}
          {isAdmin && <>
            <button onClick={prevMonth} style={navBtn}><ChevronLeft size={16}/></button>
            <span style={{fontWeight:700,fontSize:15,minWidth:150,textAlign:'center'}}>{monthName}</span>
            <button onClick={nextMonth} style={navBtn}><ChevronRight size={16}/></button>
          </>}
        </div>
      </div>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>

      {isAdmin && (
        <div style={{display:'flex',gap:16,marginBottom:16,borderBottom:'1px solid #e6e9ef'}}>
          <button onClick={() => setTab('payroll')} style={{background:'none',border:'none',borderBottom:tab==='payroll'?'2px solid #115e59':'2px solid transparent',padding:'8px 16px',fontWeight:600,color:tab==='payroll'?'#115e59':'#64748b',cursor:'pointer',fontSize:14}}>Payrolls</button>
          <button onClick={() => setTab('approvals')} style={{background:'none',border:'none',borderBottom:tab==='approvals'?'2px solid #115e59':'2px solid transparent',padding:'8px 16px',fontWeight:600,color:tab==='approvals'?'#115e59':'#64748b',cursor:'pointer',fontSize:14}}>Approvals</button>
        </div>
      )}

      {isAdmin && tab === 'payroll' && (
        <div style={{display:'flex',gap:12,marginBottom:16}}>
          <div style={{position:'relative',flex:1,maxWidth:320}}>
            <Search size={14} style={{position:'absolute',left:12,top:'50%',transform:'translateY(-50%)',color:'#94a3b8'}}/>
            <input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search employee name or code..."
              style={{width:'100%',height:38,paddingLeft:34,border:'1px solid #e6e9ef',borderRadius:9,fontSize:13,outline:'none',boxSizing:'border-box'}}/>
          </div>
          <button onClick={load} style={{height:38,padding:'0 16px',borderRadius:9,border:'none',background:'#115e59',color:'#fff',cursor:'pointer',fontSize:13,fontWeight:700}}>Search</button>
        </div>
      )}

      {tab === 'payroll' ? (
      <div style={{background:'#fff',borderRadius:12,border:'1px solid #e6e9ef',overflow:'hidden'}}>
        <div style={{padding:'12px 18px',borderBottom:'1px solid #e6e9ef',fontWeight:700,fontSize:14}}>
          {isAdmin ? `All Payrolls — ${monthName}` : 'My Payslips'} <span style={{fontWeight:400,color:'#94a3b8',fontSize:12,float:'right'}}>{rows.length} records</span>
        </div>
        {loading ? <div style={{padding:60,textAlign:'center',color:'#94a3b8'}}>Loading...</div>
        : rows.length===0 ? (
          <div style={{padding:60,textAlign:'center',color:'#94a3b8'}}>
            <FileText size={40} style={{opacity:0.3,marginBottom:12}}/>
            <div style={{fontSize:15,fontWeight:500}}>No payroll records{isAdmin?` for ${monthName}`:''}</div>
            <div style={{fontSize:13,marginTop:4}}>{isAdmin?'Click "Generate Payroll" to create from eSSL attendance. Use "Settings" to configure Month Start Day.':'Payroll appears once HR processes it'}</div>
          </div>
        ) : (
          <div style={{overflowX:'auto'}}>
            <table style={{width:'100%',borderCollapse:'collapse',minWidth:800}}>
              <thead><tr style={{background:'#f8fafc'}}>
                {(isAdmin?['Code','Name','Dept','Present','Hours','OT','Basic','Gross','Deduct','Net Pay','Status','Actions']:['Month','Present','Hours','OT','Basic','Gross','Deduct','Net Pay','Status','Payslip']).map(h=>(
                  <th key={h} style={{padding:'10px 14px',textAlign:'left',fontSize:11.5,fontWeight:700,color:'#64748b',borderBottom:'1px solid #e6e9ef',whiteSpace:'nowrap'}}>{h}</th>
                ))}
              </tr></thead>
              <tbody>
                {rows.map((p,i)=>(
                  <tr key={p.id} style={{background:i%2===0?'#fff':'#fafafa'}}>
                    {isAdmin ? <>
                      <td style={td}><span style={{fontFamily:'monospace',color:'#94a3b8',fontSize:12}}>{p.emp_code}</span></td>
                      <td style={{...td,fontWeight:600}}>{p.emp_name}</td>
                      <td style={td}>{p.dept||'—'}</td>
                    </> : (
                      <td style={{...td,fontWeight:600}}>{new Date(p.year,p.month-1).toLocaleString('default',{month:'short',year:'numeric'})}</td>
                    )}
                    <td style={td}>{p.present_days}</td>
                    <td style={{...td,fontFamily:'monospace',fontSize:12}}>{p.work_hours}</td>
                    <td style={{...td,fontFamily:'monospace',fontSize:12}}>{p.ot_hours}</td>
                    <td style={{...td,fontWeight:600}}>{fmt(p.basic_salary)}</td>
                    <td style={{...td,fontWeight:600}}>{fmt((p.earned||0)+(p.ot_amount||0))}</td>
                    <td style={{...td,fontWeight:600,color:'#dc2626'}}>{fmt(p.deductions)}</td>
                    <td style={{...td,fontWeight:800,color:'#115e59'}}>{fmt(p.net_pay)}</td>
                    <td style={td}><span style={{background:p.status==='finalized'?'#dcfce7':'#fef3c7',color:p.status==='finalized'?'#15803d':'#b45309',padding:'2px 8px',borderRadius:6,fontSize:11,fontWeight:700}}>{p.status}</span></td>
                    <td style={td}>
                      <div style={{display:'flex',gap:6}}>
                        {isAdmin && p.status!=='finalized' && (
                          <button onClick={()=>{setEditRow(p);setSalary(p.basic_salary||'');setDeductions(p.deductions||'');}} style={{fontSize:11,padding:'4px 10px',borderRadius:6,border:'1px solid #115e59',background:'#fff',color:'#115e59',cursor:'pointer',fontWeight:700}}>Set Salary</button>
                        )}
                        <button onClick={()=>setViewSlip(p)} style={{fontSize:11,padding:'4px 10px',borderRadius:6,border:'none',background:'#eff6ff',color:'#1d4ed8',cursor:'pointer',fontWeight:700}}>Payslip</button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
      ) : (
      <div style={{background:'#fff',borderRadius:12,border:'1px solid #e6e9ef',overflow:'hidden'}}>
        <div style={{padding:'12px 18px',borderBottom:'1px solid #e6e9ef',fontWeight:700,fontSize:14}}>Pending Approvals</div>
        {approvals.length === 0 ? (
          <div style={{padding:60,textAlign:'center',color:'#94a3b8'}}>No pending approvals.</div>
        ) : (
          <table style={{width:'100%',borderCollapse:'collapse'}}>
            <thead><tr style={{background:'#f8fafc'}}>
              {['Code','Name','Basic Salary','HRA','Date','Actions'].map(h=>(
                <th key={h} style={{padding:'10px 14px',textAlign:'left',fontSize:11.5,fontWeight:700,color:'#64748b',borderBottom:'1px solid #e6e9ef'}}>{h}</th>
              ))}
            </tr></thead>
            <tbody>
              {approvals.map((a, i) => (
                <tr key={a.id} style={{background:i%2===0?'#fff':'#fafafa'}}>
                  <td style={td}>{a.emp_code}</td>
                  <td style={{...td,fontWeight:600}}>{a.emp_name}</td>
                  <td style={{...td,fontWeight:600}}>{fmt(a.basic_salary)}</td>
                  <td style={{...td,fontWeight:600}}>{fmt(a.hra)}</td>
                  <td style={td}>{new Date(a.created_at).toLocaleDateString()}</td>
                  <td style={td}>
                    <div style={{display:'flex',gap:6}}>
                      <button onClick={()=>handleApprove(a.id, 'approve')} style={{fontSize:11,padding:'4px 10px',borderRadius:6,border:'none',background:'#16a34a',color:'#fff',cursor:'pointer',fontWeight:700}}>Approve</button>
                      <button onClick={()=>handleApprove(a.id, 'reject')} style={{fontSize:11,padding:'4px 10px',borderRadius:6,border:'none',background:'#dc2626',color:'#fff',cursor:'pointer',fontWeight:700}}>Reject</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
      )}

      {viewSlip && <PayslipModal slip={viewSlip} onClose={()=>setViewSlip(null)}/>}

      {editRow && (
        <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.4)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000}}>
          <div style={{background:'#fff',borderRadius:16,padding:28,width:360}}>
            <h3 style={{fontWeight:800,marginBottom:6}}>Set Salary</h3>
            <p style={{fontSize:13,color:'#64748b',marginBottom:16}}>{editRow.emp_name} ({editRow.emp_code})</p>
            <div style={{marginBottom:12}}>
              <label style={{fontSize:12,fontWeight:600,color:'#4b5566',display:'block',marginBottom:4}}>Monthly Basic Salary (₹)</label>
              <input type="number" value={salary} onChange={e=>setSalary(e.target.value)} style={{width:'100%',height:40,padding:'0 12px',border:'1.5px solid #e6e9ef',borderRadius:8,fontSize:14,outline:'none',boxSizing:'border-box'}}/>
            </div>
            <div style={{marginBottom:12}}>
              <label style={{fontSize:12,fontWeight:600,color:'#4b5566',display:'block',marginBottom:4}}>HRA (₹)</label>
              <input type="number" value={hra} onChange={e=>setHra(e.target.value)} style={{width:'100%',height:40,padding:'0 12px',border:'1.5px solid #e6e9ef',borderRadius:8,fontSize:14,outline:'none',boxSizing:'border-box'}}/>
            </div>
            <div style={{marginBottom:18}}>
              <label style={{fontSize:12,fontWeight:600,color:'#4b5566',display:'block',marginBottom:4}}>Deductions (₹)</label>
              <input type="number" value={deductions} onChange={e=>setDeductions(e.target.value)} style={{width:'100%',height:40,padding:'0 12px',border:'1.5px solid #e6e9ef',borderRadius:8,fontSize:14,outline:'none',boxSizing:'border-box'}}/>
            </div>
            <div style={{display:'flex',gap:10}}>
              <button onClick={()=>setEditRow(null)} style={{flex:1,height:42,borderRadius:9,border:'1.5px solid #e6e9ef',background:'#fff',cursor:'pointer',fontWeight:600}}>Cancel</button>
              <button onClick={saveSalary} style={{flex:2,height:42,borderRadius:9,border:'none',background:'#115e59',color:'#fff',cursor:'pointer',fontWeight:700}}>
                {editRow.basic_salary > 0 ? 'Submit for Approval' : 'Save & Calculate'}
              </button>
            </div>
          </div>
        </div>
      )}
      
      {/* Settings Modal */}
      {showSettings && (
        <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.4)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000}}>
          <div style={{background:'#fff',borderRadius:16,padding:28,width:360,boxShadow:'0 20px 60px rgba(0,0,0,0.2)'}}>
            <div style={{display:'flex',justifyContent:'space-between',marginBottom:20}}>
              <h3 style={{fontWeight:800}}>Payroll Settings</h3>
              <button onClick={()=>setShowSettings(false)} style={{background:'none',border:'none',cursor:'pointer'}}><X size={18} color="#64748b"/></button>
            </div>
            
            <div style={{marginBottom:22}}>
              <label style={{fontSize:12,fontWeight:600,color:'#4b5566',display:'block',marginBottom:4}}>Month Start Day (Payroll Cycle)</label>
              <input type="number" min="1" max="28" value={monthStartDay} onChange={e=>setMonthStartDay(parseInt(e.target.value))} style={{width:'100%',height:40,padding:'0 12px',border:'1.5px solid #e6e9ef',borderRadius:8,fontSize:14,outline:'none',boxSizing:'border-box'}}/>
              <p style={{fontSize:11,color:'#94a3b8',marginTop:6}}>e.g., set to 26 if your cycle is 26th to 25th. Set to 1 for standard calendar month.</p>
            </div>
            
            <div style={{display:'flex',gap:10}}>
              <button onClick={()=>setShowSettings(false)} style={{flex:1,height:42,borderRadius:9,border:'1.5px solid #e6e9ef',background:'#fff',cursor:'pointer',fontWeight:600}}>Cancel</button>
              <button onClick={saveSettings} disabled={savingSettings} style={{flex:1,height:42,borderRadius:9,border:'none',background:'#115e59',color:'#fff',cursor:'pointer',fontWeight:700}}>
                {savingSettings ? 'Saving...' : 'Save Settings'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
const navBtn = {width:34,height:34,borderRadius:8,border:'1px solid #e6e9ef',background:'#fff',cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'};
const td = {padding:'9px 14px',borderBottom:'1px solid #f1f5f9',fontSize:13,whiteSpace:'nowrap',verticalAlign:'middle'};
