import React, { useState, useEffect, useCallback } from 'react';
import { ChevronLeft, ChevronRight, DollarSign, Download, RefreshCw, Search, FileText, X, Settings, Edit2, CheckCircle, Lock, Unlock } from 'lucide-react';
import useAuthStore from '../store/authStore';
import { settingsApi } from '../utils/api';

const API = '/api';
const auth = () => ({ Authorization: `Bearer ${localStorage.getItem('hrms_token')}` });
const fmt = n => '₹' + Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 });
const fmt2 = n => '₹' + Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

// ─── Payslip Modal ──────────────────────────────────────────────────
function PayslipModal({ slip, onClose }) {
  if (!slip) return null;
  const monthName = new Date(slip.year, slip.month - 1).toLocaleString('default', { month: 'long', year: 'numeric' });

  const earnings = [
    ['Basic (Earned)', slip.earned_basic],
    ['HRA', slip.hra_amount],
    ['DA', slip.da_amount],
    ['OT Amount', slip.ot_amount],
  ];
  const deductions = [
    ['PF (Employee 12%)', slip.pf],
    ['ESIC (0.75%)', slip.esic],
    ['Advance', slip.advance],
    ['Other Deductions', slip.other_deductions],
  ];

  const print = () => {
    const w = window.open('', '_blank');
    const earningsRows = earnings.map(([l, v]) =>
      `<tr><td class="lbl">${l}</td><td class="val">${fmt2(v)}</td></tr>`).join('');
    const dedRows = deductions.filter(([, v]) => v > 0).map(([l, v]) =>
      `<tr><td class="lbl">${l}</td><td class="val">- ${fmt2(v)}</td></tr>`).join('');
    w.document.write(`<html><head><title>Payslip ${slip.emp_code}</title>
      <style>
        body{font-family:Arial;padding:40px;max-width:640px;margin:0 auto;color:#1e293b}
        h2{color:#115e59;border-bottom:2px solid #115e59;padding-bottom:8px;margin-bottom:4px}
        .meta{color:#64748b;font-size:13px;margin-bottom:20px}
        h4{margin:16px 0 4px;font-size:13px;text-transform:uppercase;color:#94a3b8;letter-spacing:1px}
        table{width:100%;border-collapse:collapse;margin:0 0 8px}
        td{padding:7px 10px;border-bottom:1px solid #f1f5f9;font-size:13.5px}
        .lbl{color:#475569}.val{text-align:right;font-weight:600}
        .gross-row td{background:#f0fdf4;font-weight:700;color:#15803d;font-size:14px}
        .net-row td{background:#eff6ff;font-weight:800;color:#1d4ed8;font-size:16px}
        .footer{color:#94a3b8;font-size:11px;margin-top:20px}
      </style></head><body>
      <h2>East Coast Hospitals Ltd — Payslip</h2>
      <div class="meta"><b>${slip.emp_name}</b> (${slip.emp_code}) &nbsp;·&nbsp; ${slip.dept || ''} &nbsp;·&nbsp; ${monthName}</div>
      <table>
        <tr><td class="lbl">Present Days</td><td class="val">${slip.present_days}</td></tr>
        <tr><td class="lbl">OT Hours</td><td class="val">${slip.ot_hours}</td></tr>
      </table>
      <h4>Earnings</h4>
      <table>${earningsRows}
        <tr class="gross-row"><td>GROSS PAY</td><td class="val">${fmt2(slip.gross)}</td></tr>
      </table>
      <h4>Deductions</h4>
      <table>${dedRows}
        <tr><td class="lbl" style="font-weight:700">Total Deductions</td><td class="val" style="color:#dc2626">- ${fmt2(slip.deductions)}</td></tr>
      </table>
      <table>
        <tr class="net-row"><td>NET PAY</td><td class="val">${fmt2(slip.net_pay)}</td></tr>
      </table>
      <p class="footer">Generated by EastCoast HRMS &middot; ${new Date().toLocaleString('en-IN')}</p>
      <script>window.print()</script></body></html>`);
    w.document.close();
  };

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.55)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: '#fff', borderRadius: 18, padding: '28px 28px 22px', width: 460, maxHeight: '90vh', overflowY: 'auto', boxShadow: '0 24px 60px rgba(0,0,0,0.25)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10 }}>
          <div>
            <h3 style={{ fontWeight: 800, fontSize: 17, margin: 0 }}>Payslip — {monthName}</h3>
            <p style={{ fontSize: 12, color: '#64748b', margin: '2px 0 0' }}>{slip.emp_name} · {slip.emp_code} · {slip.dept || '—'}</p>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 4 }}><X size={18} /></button>
        </div>

        {/* Attendance */}
        <div style={{ background: '#f8fafc', borderRadius: 10, padding: '10px 14px', marginBottom: 14, display: 'flex', gap: 20, fontSize: 13 }}>
          <div><span style={{ color: '#64748b' }}>Present: </span><b>{slip.present_days} days</b></div>
          <div><span style={{ color: '#64748b' }}>OT: </span><b>{slip.ot_hours}h</b></div>
        </div>

        {/* Earnings */}
        <div style={{ fontWeight: 700, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1, color: '#94a3b8', marginBottom: 6 }}>Earnings</div>
        {earnings.map(([l, v]) => (
          <div key={l} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 4px', borderBottom: '1px solid #f1f5f9', fontSize: 13.5 }}>
            <span style={{ color: '#475569' }}>{l}</span>
            <span style={{ fontWeight: 600 }}>{fmt2(v)}</span>
          </div>
        ))}
        <div style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 4px', background: '#f0fdf4', borderRadius: 8, margin: '6px 0 14px', fontSize: 14, fontWeight: 800, color: '#15803d', paddingLeft: 8, paddingRight: 8 }}>
          <span>GROSS PAY</span><span>{fmt2(slip.gross)}</span>
        </div>

        {/* Deductions */}
        <div style={{ fontWeight: 700, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1, color: '#94a3b8', marginBottom: 6 }}>Deductions</div>
        {deductions.filter(([, v]) => v > 0).map(([l, v]) => (
          <div key={l} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 4px', borderBottom: '1px solid #f1f5f9', fontSize: 13.5 }}>
            <span style={{ color: '#475569' }}>{l}</span>
            <span style={{ fontWeight: 600, color: '#dc2626' }}>- {fmt2(v)}</span>
          </div>
        ))}
        <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 8px', fontSize: 13, fontWeight: 700, color: '#dc2626', marginBottom: 14 }}>
          <span>Total Deductions</span><span>- {fmt2(slip.deductions)}</span>
        </div>

        {/* Net Pay */}
        <div style={{ display: 'flex', justifyContent: 'space-between', padding: '14px 12px', background: 'linear-gradient(135deg,#115e59,#1d4ed8)', borderRadius: 12, fontSize: 18, fontWeight: 800, color: '#fff', marginBottom: 18 }}>
          <span>NET PAY</span><span>{fmt2(slip.net_pay)}</span>
        </div>

        <button onClick={print} style={{ width: '100%', height: 44, borderRadius: 10, border: 'none', background: '#115e59', color: '#fff', fontWeight: 700, cursor: 'pointer', fontSize: 14, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
          <Download size={15} /> Download / Print Payslip
        </button>
      </div>
    </div>
  );
}

// ─── Edit Payroll Modal ──────────────────────────────────────────────
function EditModal({ row, formula, onClose, onSaved }) {
  const [basic, setBasic] = useState(row.basic_salary || '');
  const [advance, setAdvance] = useState(row.advance || 0);
  const [otherDed, setOtherDed] = useState(row.other_deductions || 0);
  const [presentDays, setPresentDays] = useState(row.present_days || 0);
  const [saving, setSaving] = useState(false);
  const [msg, setMsg] = useState('');

  // Live preview calculation
  const ctc = parseFloat(basic) || 0;
  const present = parseInt(presentDays) || 0;
  const ratio = present / 30;
  const basicPct = (formula?.basic_pct || 60) / 100;
  const hraPct = (formula?.hra_pct || 20) / 100;
  const daPct = (formula?.da_pct || 20) / 100;
  const pfPct = (formula?.pf_pct || 12) / 100;
  const esicPct = (formula?.esic_pct || 0.75) / 100;

  const earnedBasic = ctc * basicPct * ratio;
  const hraAmt = ctc * hraPct * ratio;
  const daAmt = ctc * daPct * ratio;
  const otAmt = row.ot_amount || 0;
  const gross = earnedBasic + hraAmt + daAmt + otAmt;
  const pf = earnedBasic * pfPct;
  const esic = earnedBasic * esicPct;
  const adv = parseFloat(advance) || 0;
  const otherD = parseFloat(otherDed) || 0;
  const totalDed = pf + esic + adv + otherD;
  const netPay = gross - totalDed;

  const save = async () => {
    setSaving(true); setMsg('');
    try {
      const r = await fetch(`${API}/payroll/${row.id}`, {
        method: 'PUT',
        headers: { ...auth(), 'Content-Type': 'application/json' },
        body: JSON.stringify({
          basic_salary: ctc || null,
          advance: adv,
          other_deductions: otherD,
          present_days: present,
        }),
      });
      const d = await r.json();
      if (r.ok) { onSaved(d); onClose(); }
      else setMsg(d.detail || 'Save failed');
    } catch { setMsg('Network error'); }
    setSaving(false);
  };

  const row2 = (label, val, color) => (
    <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', fontSize: 13, borderBottom: '1px solid #f1f5f9' }}>
      <span style={{ color: '#64748b' }}>{label}</span>
      <span style={{ fontWeight: 700, color: color || '#0b1320' }}>{fmt2(val)}</span>
    </div>
  );

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: '#fff', borderRadius: 18, padding: 28, width: 540, maxHeight: '92vh', overflowY: 'auto', boxShadow: '0 24px 60px rgba(0,0,0,0.25)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 18 }}>
          <div>
            <h3 style={{ fontWeight: 800, margin: 0 }}>Edit Payroll</h3>
            <p style={{ fontSize: 12, color: '#64748b', margin: '2px 0 0' }}>{row.emp_name} ({row.emp_code}) · {row.dept}</p>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer' }}><X size={18} /></button>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 }}>
          <div>
            <label style={lbl}>Monthly CTC / Gross Salary (₹) <span style={{fontWeight:400,color:'#94a3b8'}}>(Full package — Basic+HRA+DA)</span></label>
            <input type="number" value={basic} onChange={e => setBasic(e.target.value)} style={inp} placeholder="e.g. 20000" />
          </div>
          <div>
            <label style={lbl}>Present Days (override)</label>
            <input type="number" min="0" max="31" value={presentDays} onChange={e => setPresentDays(e.target.value)} style={inp} />
          </div>
          <div>
            <label style={lbl}>Advance Deduction (₹)</label>
            <input type="number" value={advance} onChange={e => setAdvance(e.target.value)} style={inp} placeholder="0" />
          </div>
          <div>
            <label style={lbl}>Other Deductions (₹)</label>
            <input type="number" value={otherDed} onChange={e => setOtherDed(e.target.value)} style={inp} placeholder="0" />
          </div>
        </div>

        {/* Live Preview */}
        <div style={{ background: '#f8fafc', borderRadius: 12, padding: '14px 16px', marginBottom: 18 }}>
          <div style={{ fontWeight: 700, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1, color: '#94a3b8', marginBottom: 10 }}>Live Preview</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0 24px' }}>
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: '#16a34a', marginBottom: 4 }}>EARNINGS</div>
              {row2(`Basic (${formula?.basic_pct || 60}% of CTC)`, earnedBasic, '#15803d')}
              {row2(`HRA (${formula?.hra_pct || 20}% of CTC)`, hraAmt)}
              {row2(`DA (${formula?.da_pct || 20}% of CTC)`, daAmt)}
              {row2('OT Amount', otAmt)}
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '7px 0', fontSize: 13.5, fontWeight: 800, color: '#16a34a', borderTop: '2px solid #dcfce7', marginTop: 4 }}>
                <span>Gross</span><span>{fmt2(gross)}</span>
              </div>
            </div>
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: '#dc2626', marginBottom: 4 }}>DEDUCTIONS</div>
              {row2(`PF (${formula?.pf_pct || 12}%)`, pf, '#dc2626')}
              {row2(`ESIC (${formula?.esic_pct || 0.75}%)`, esic, '#dc2626')}
              {row2('Advance', adv, '#dc2626')}
              {row2('Other', otherD, '#dc2626')}
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '7px 0', fontSize: 13.5, fontWeight: 800, color: '#dc2626', borderTop: '2px solid #fee2e2', marginTop: 4 }}>
                <span>Total Ded.</span><span>- {fmt2(totalDed)}</span>
              </div>
            </div>
          </div>
          <div style={{ marginTop: 12, display: 'flex', justifyContent: 'space-between', padding: '12px 14px', background: 'linear-gradient(135deg,#115e59,#1d4ed8)', borderRadius: 10, color: '#fff', fontWeight: 800, fontSize: 16 }}>
            <span>NET PAY</span><span>{fmt2(netPay)}</span>
          </div>
        </div>

        {msg && <div style={{ color: '#dc2626', fontSize: 13, marginBottom: 12 }}>{msg}</div>}

        <div style={{ display: 'flex', gap: 10 }}>
          <button onClick={onClose} style={{ flex: 1, height: 44, borderRadius: 10, border: '1.5px solid #e6e9ef', background: '#fff', cursor: 'pointer', fontWeight: 600 }}>Cancel</button>
          <button onClick={save} disabled={saving} style={{ flex: 2, height: 44, borderRadius: 10, border: 'none', background: '#115e59', color: '#fff', cursor: saving ? 'not-allowed' : 'pointer', fontWeight: 700, fontSize: 14 }}>
            {saving ? 'Saving...' : '✓ Save & Recalculate'}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Payroll Formula Settings Modal ─────────────────────────────────
function FormulaSettingsModal({ onClose, onSaved }) {
  const [form, setForm] = useState({ basic_pct: 60, hra_pct: 20, da_pct: 20, pf_pct: 12, esic_pct: 0.75, ot_hours_divisor: 8 });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [msg, setMsg] = useState('');

  useEffect(() => {
    fetch(`${API}/payroll/formula`, { headers: auth() })
      .then(r => r.json()).then(d => { setForm(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const total = (form.basic_pct || 0) + (form.hra_pct || 0) + (form.da_pct || 0);
  const totalOk = Math.abs(total - 100) < 0.01;

  const save = async () => {
    if (!totalOk) { setMsg(`Basic + HRA + DA must equal 100%. Currently: ${total.toFixed(1)}%`); return; }
    setSaving(true); setMsg('');
    try {
      const r = await fetch(`${API}/payroll/formula`, {
        method: 'POST', headers: { ...auth(), 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      });
      const d = await r.json();
      if (r.ok) { onSaved(); onClose(); }
      else setMsg(d.detail || 'Save failed');
    } catch { setMsg('Network error'); }
    setSaving(false);
  };

  const fi = (key, label, hint) => (
    <div style={{ marginBottom: 14 }}>
      <label style={lbl}>{label}</label>
      <input type="number" step="0.01" value={form[key]} onChange={e => setForm(f => ({ ...f, [key]: parseFloat(e.target.value) || 0 }))} style={inp} />
      {hint && <p style={{ fontSize: 11, color: '#94a3b8', margin: '3px 0 0' }}>{hint}</p>}
    </div>
  );

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: '#fff', borderRadius: 18, padding: 28, width: 480, boxShadow: '0 24px 60px rgba(0,0,0,0.25)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
          <div>
            <h3 style={{ fontWeight: 800, margin: 0 }}>Payroll Formula Settings</h3>
            <p style={{ fontSize: 12, color: '#64748b', margin: '2px 0 0' }}>Configure percentage breakdown for all salary components</p>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer' }}><X size={18} /></button>
        </div>

        {loading ? <div style={{ textAlign: 'center', padding: 30 }}>Loading...</div> : <>
          <div style={{ background: '#f0fdf4', borderRadius: 10, padding: '12px 16px', marginBottom: 18 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: '#15803d', marginBottom: 6 }}>📊 CTC SPLIT — Earnings (Basic + HRA + DA must total 100% of CTC)</div>
            <p style={{ fontSize: 11, color: '#64748b', margin: '0 0 10px' }}>CTC = ₹20,000 → Basic = 60% = ₹12,000 &nbsp;|&nbsp; HRA = 20% = ₹4,000 &nbsp;|&nbsp; DA = 20% = ₹4,000</p>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
              <div>
                <label style={lbl}>Basic (% of CTC)</label>
                <input type="number" value={form.basic_pct} onChange={e => setForm(f => ({ ...f, basic_pct: parseFloat(e.target.value) || 0 }))} style={{ ...inp, borderColor: totalOk ? '#e6e9ef' : '#fca5a5' }} />
              </div>
              <div>
                <label style={lbl}>HRA (% of CTC)</label>
                <input type="number" value={form.hra_pct} onChange={e => setForm(f => ({ ...f, hra_pct: parseFloat(e.target.value) || 0 }))} style={{ ...inp, borderColor: totalOk ? '#e6e9ef' : '#fca5a5' }} />
              </div>
              <div>
                <label style={lbl}>DA (% of CTC)</label>
                <input type="number" value={form.da_pct} onChange={e => setForm(f => ({ ...f, da_pct: parseFloat(e.target.value) || 0 }))} style={{ ...inp, borderColor: totalOk ? '#e6e9ef' : '#fca5a5' }} />
              </div>
            </div>
            <div style={{ marginTop: 8, fontSize: 13, fontWeight: 600, color: totalOk ? '#16a34a' : '#dc2626' }}>
              {totalOk ? `✅ Total: ${total.toFixed(1)}% — Correct!` : `⚠️ Total: ${total.toFixed(1)}% — Must be 100%`}
            </div>
          </div>

          <div style={{ background: '#fff1f2', borderRadius: 10, padding: '12px 16px', marginBottom: 18 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: '#be123c', marginBottom: 4 }}>📉 DEDUCTIONS (% of Basic Earned only — not HRA/DA)</div>
            <p style={{ fontSize: 11, color: '#64748b', margin: '0 0 10px' }}>PF &amp; ESIC are applied on the Basic component only, as per your note.</p>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
              <div>
                <label style={lbl}>PF (%)</label>
                <input type="number" step="0.01" value={form.pf_pct} onChange={e => setForm(f => ({ ...f, pf_pct: parseFloat(e.target.value) || 0 }))} style={inp} />
              </div>
              <div>
                <label style={lbl}>ESIC (%)</label>
                <input type="number" step="0.01" value={form.esic_pct} onChange={e => setForm(f => ({ ...f, esic_pct: parseFloat(e.target.value) || 0 }))} style={inp} />
              </div>
              <div>
                <label style={lbl}>OT per X hrs</label>
                <input type="number" step="0.5" value={form.ot_hours_divisor} onChange={e => setForm(f => ({ ...f, ot_hours_divisor: parseFloat(e.target.value) || 8 }))} style={inp} />
                <p style={{ fontSize: 10, color: '#94a3b8', margin: '2px 0 0' }}>OT rate = per_day ÷ this</p>
              </div>
            </div>
          </div>

          {msg && <div style={{ color: '#dc2626', fontSize: 13, marginBottom: 12 }}>{msg}</div>}
          <div style={{ display: 'flex', gap: 10 }}>
            <button onClick={onClose} style={{ flex: 1, height: 44, borderRadius: 10, border: '1.5px solid #e6e9ef', background: '#fff', cursor: 'pointer', fontWeight: 600 }}>Cancel</button>
            <button onClick={save} disabled={saving || !totalOk} style={{ flex: 2, height: 44, borderRadius: 10, border: 'none', background: totalOk ? '#115e59' : '#94a3b8', color: '#fff', cursor: (saving || !totalOk) ? 'not-allowed' : 'pointer', fontWeight: 700 }}>
              {saving ? 'Saving...' : '✓ Save Formula'}
            </button>
          </div>
        </>}
      </div>
    </div>
  );
}

// ─── Main Payroll Page ──────────────────────────────────────────────
export default function Payroll() {
  const { user } = useAuthStore();
  const isAdmin = ['hr_admin', 'it_admin'].includes(user?.role);
  const now = new Date();
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [year, setYear] = useState(now.getFullYear());
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [msg, setMsg] = useState('');
  const [search, setSearch] = useState('');
  const [viewSlip, setViewSlip] = useState(null);
  const [editRow, setEditRow] = useState(null);
  const [formula, setFormula] = useState(null);
  const [showFormulaSettings, setShowFormulaSettings] = useState(false);
  const [showReports, setShowReports] = useState(false);
  const [tab, setTab] = useState('payroll');
  const [approvals, setApprovals] = useState([]);

  const loadFormula = useCallback(async () => {
    try {
      const r = await fetch(`${API}/payroll/formula`, { headers: auth() });
      if (r.ok) setFormula(await r.json());
    } catch {}
  }, []);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const url = isAdmin
        ? `${API}/payroll/list?month=${month}&year=${year}${search ? '&search=' + encodeURIComponent(search) : ''}`
        : `${API}/payroll/my-slips`;
      const r = await fetch(url, { headers: auth() });
      const d = await r.json();
      setRows(Array.isArray(d) ? d : []);
    } catch { setRows([]); }
    setLoading(false);
  }, [month, year, search, isAdmin]);

  const loadApprovals = async () => {
    try {
      const r = await fetch(`${API}/payroll/revisions/pending`, { headers: auth() });
      const d = await r.json();
      setApprovals(Array.isArray(d) ? d : []);
    } catch {}
  };

  useEffect(() => {
    if (isAdmin) loadFormula();
  }, [isAdmin, loadFormula]);

  useEffect(() => {
    if (tab === 'payroll') load();
    if (tab === 'approvals') loadApprovals();
  }, [month, year, tab, load]);

  const handleGenerate = async () => {
    setGenerating(true); setMsg('');
    try {
      const r = await fetch(`${API}/payroll/generate?month=${month}&year=${year}`, { method: 'POST', headers: auth() });
      const d = await r.json();
      setMsg(r.ok ? `✅ ${d.message} (${d.created} new, ${d.updated} updated)` : `❌ ${d.detail}`);
      load();
    } catch { setMsg('❌ Generate failed'); }
    setGenerating(false);
    setTimeout(() => setMsg(''), 8000);
  };

  const handleFinalize = async (id, action) => {
    await fetch(`${API}/payroll/${id}/${action}`, { method: 'POST', headers: auth() });
    load();
  };

  const handleApprove = async (id, action) => {
    await fetch(`${API}/payroll/revisions/${id}/${action}`, { method: 'POST', headers: auth() });
    loadApprovals(); load();
  };

  const onSaved = (updated) => {
    setRows(rows => rows.map(r => r.id === updated.id ? updated : r));
  };

  const prevMonth = () => { if (month === 1) { setMonth(12); setYear(y => y - 1); } else setMonth(m => m - 1); };
  const nextMonth = () => { if (month === 12) { setMonth(1); setYear(y => y + 1); } else setMonth(m => m + 1); };
  const monthName = new Date(year, month - 1).toLocaleString('default', { month: 'long', year: 'numeric' });

  return (
    <div>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>

      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, flexWrap: 'wrap', gap: 10 }}>
        <div>
          <h1 style={{ fontSize: 22, fontWeight: 800, color: '#0b1320', margin: 0 }}>Payroll</h1>
          <p style={{ color: '#64748b', fontSize: 13, marginTop: 2 }}>{isAdmin ? 'Generate & manage payroll from eSSL attendance' : 'Your payslips'}</p>
        </div>

        {isAdmin && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
            {msg && <span style={{ fontSize: 12, fontWeight: 600, color: msg.startsWith('✅') ? '#16a34a' : '#dc2626', maxWidth: 280 }}>{msg}</span>}

            {/* Reports dropdown */}
            <div style={{ position: 'relative' }}>
              <button onClick={() => setShowReports(!showReports)} style={btnOutline}>
                <Download size={13} /> Reports
              </button>
              {showReports && (
                <div style={{ position: 'absolute', top: '100%', right: 0, marginTop: 6, background: '#fff', border: '1px solid #e6e9ef', borderRadius: 10, boxShadow: '0 10px 28px rgba(0,0,0,0.1)', width: 190, zIndex: 100 }}>
                  {[['Monthly', 'monthly'], ['PF Report', 'pf'], ['ESIC Report', 'esic'], ['PT Report', 'pt'], ['Bank Transfer', 'bank']].map(([label, key]) => (
                    <a key={key} href={`/api/payroll/reports/${key}?month=${month}&year=${year}&token=${localStorage.getItem('hrms_token')}`}
                      target="_blank" rel="noreferrer"
                      style={{ display: 'block', padding: '10px 16px', color: '#0b1320', fontSize: 13, textDecoration: 'none', borderBottom: '1px solid #f1f5f9' }}
                      onClick={() => setShowReports(false)}>{label}</a>
                  ))}
                </div>
              )}
            </div>

            <button onClick={() => setShowFormulaSettings(true)} style={btnOutline}>
              <Settings size={13} /> Formula Settings
            </button>

            <button onClick={handleGenerate} disabled={generating} style={{ ...btnPrimary, background: generating ? '#9fb7b4' : '#115e59', cursor: generating ? 'not-allowed' : 'pointer' }}>
              <RefreshCw size={13} style={{ animation: generating ? 'spin 1s linear infinite' : 'none' }} />
              {generating ? 'Generating...' : 'Generate Payroll'}
            </button>

            <button onClick={prevMonth} style={navBtn}><ChevronLeft size={16} /></button>
            <span style={{ fontWeight: 700, fontSize: 15, minWidth: 150, textAlign: 'center' }}>{monthName}</span>
            <button onClick={nextMonth} style={navBtn}><ChevronRight size={16} /></button>
          </div>
        )}
      </div>

      {/* Tabs */}
      {isAdmin && (
        <div style={{ display: 'flex', gap: 4, marginBottom: 16, borderBottom: '1px solid #e6e9ef' }}>
          {[['payroll', 'Payrolls'], ['approvals', 'Salary Approvals']].map(([key, label]) => (
            <button key={key} onClick={() => setTab(key)}
              style={{ background: 'none', border: 'none', borderBottom: tab === key ? '2px solid #115e59' : '2px solid transparent', padding: '8px 18px', fontWeight: 600, color: tab === key ? '#115e59' : '#64748b', cursor: 'pointer', fontSize: 14 }}>
              {label}
            </button>
          ))}
        </div>
      )}

      {/* Search bar */}
      {isAdmin && tab === 'payroll' && (
        <div style={{ display: 'flex', gap: 10, marginBottom: 16 }}>
          <div style={{ position: 'relative', flex: 1, maxWidth: 320 }}>
            <Search size={13} style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', color: '#94a3b8' }} />
            <input value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && load()}
              placeholder="Search name or code..." style={{ width: '100%', height: 38, paddingLeft: 34, border: '1px solid #e6e9ef', borderRadius: 9, fontSize: 13, outline: 'none', boxSizing: 'border-box' }} />
          </div>
          <button onClick={load} style={{ ...btnPrimary }}>Search</button>
        </div>
      )}

      {/* Payroll Table */}
      {tab === 'payroll' && (
        <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #e6e9ef', overflow: 'hidden' }}>
          <div style={{ padding: '12px 18px', borderBottom: '1px solid #e6e9ef', fontWeight: 700, fontSize: 14, display: 'flex', justifyContent: 'space-between' }}>
            <span>{isAdmin ? `All Payrolls — ${monthName}` : 'My Payslips'}</span>
            <span style={{ fontWeight: 400, color: '#94a3b8', fontSize: 12 }}>{rows.length} records</span>
          </div>
          {loading ? (
            <div style={{ padding: 60, textAlign: 'center', color: '#94a3b8' }}>Loading...</div>
          ) : rows.length === 0 ? (
            <div style={{ padding: 60, textAlign: 'center', color: '#94a3b8' }}>
              <FileText size={40} style={{ opacity: 0.3, marginBottom: 12 }} />
              <div style={{ fontSize: 15, fontWeight: 500 }}>No payroll records{isAdmin ? ` for ${monthName}` : ''}</div>
              <div style={{ fontSize: 13, marginTop: 4 }}>{isAdmin ? 'Click "Generate Payroll" to create from eSSL attendance.' : 'Payroll appears once HR processes it.'}</div>
            </div>
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 900 }}>
                <thead>
                  <tr style={{ background: '#f8fafc' }}>
                    {(isAdmin
                      ? ['Code', 'Name', 'Dept', 'Present', 'OT hrs', 'CTC', 'Basic Earned', 'HRA', 'DA', 'Gross', 'PF', 'ESIC', 'Adv/Other', 'Net Pay', 'Status', 'Actions']
                      : ['Month', 'Present', 'OT hrs', 'Gross', 'Deductions', 'Net Pay', 'Status', 'Payslip']
                    ).map(h => (
                      <th key={h} style={{ padding: '10px 12px', textAlign: 'left', fontSize: 11, fontWeight: 700, color: '#64748b', borderBottom: '1px solid #e6e9ef', whiteSpace: 'nowrap' }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {rows.map((p, i) => (
                    <tr key={p.id} style={{ background: i % 2 === 0 ? '#fff' : '#fafafa' }}>
                      {isAdmin ? <>
                        <td style={td}><span style={{ fontFamily: 'monospace', color: '#94a3b8', fontSize: 11 }}>{p.emp_code}</span></td>
                        <td style={{ ...td, fontWeight: 600 }}>{p.emp_name}</td>
                        <td style={{ ...td, fontSize: 11 }}>{p.dept || '—'}</td>
                        <td style={{ ...td, textAlign: 'center' }}>{p.present_days}</td>
                        <td style={{ ...td, textAlign: 'center', fontFamily: 'monospace', fontSize: 11 }}>{p.ot_hours}</td>
                        <td style={td}>{fmt(p.basic_salary)}</td>
                        <td style={{ ...td, color: '#15803d', fontWeight: 600 }}>{fmt(p.earned_basic)}</td>
                        <td style={td}>{fmt(p.hra_amount)}</td>
                        <td style={td}>{fmt(p.da_amount)}</td>
                        <td style={{ ...td, fontWeight: 700 }}>{fmt(p.gross)}</td>
                        <td style={{ ...td, color: '#dc2626', fontSize: 11 }}>{fmt(p.pf)}</td>
                        <td style={{ ...td, color: '#dc2626', fontSize: 11 }}>{fmt(p.esic)}</td>
                        <td style={{ ...td, color: '#dc2626', fontSize: 11 }}>{fmt((p.advance || 0) + (p.other_deductions || 0))}</td>
                        <td style={{ ...td, fontWeight: 800, color: '#115e59', fontSize: 14 }}>{fmt(p.net_pay)}</td>
                        <td style={td}>
                          <span style={{ background: p.status === 'finalized' ? '#dcfce7' : '#fef3c7', color: p.status === 'finalized' ? '#15803d' : '#b45309', padding: '2px 8px', borderRadius: 6, fontSize: 11, fontWeight: 700 }}>
                            {p.status}
                          </span>
                        </td>
                        <td style={td}>
                          <div style={{ display: 'flex', gap: 5 }}>
                            {/* EDIT — always visible for draft */}
                            {p.status !== 'finalized' && (
                              <button onClick={() => setEditRow(p)}
                                style={{ fontSize: 11, padding: '4px 9px', borderRadius: 6, border: 'none', background: '#1d4ed8', color: '#fff', cursor: 'pointer', fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4 }}>
                                <Edit2 size={10} /> Edit
                              </button>
                            )}
                            <button onClick={() => setViewSlip(p)}
                              style={{ fontSize: 11, padding: '4px 9px', borderRadius: 6, border: 'none', background: '#eff6ff', color: '#1d4ed8', cursor: 'pointer', fontWeight: 700 }}>
                              Slip
                            </button>
                            {p.status !== 'finalized' ? (
                              <button onClick={() => handleFinalize(p.id, 'finalize')}
                                style={{ fontSize: 11, padding: '4px 9px', borderRadius: 6, border: 'none', background: '#dcfce7', color: '#15803d', cursor: 'pointer', fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4 }}>
                                <Lock size={10} /> Lock
                              </button>
                            ) : (
                              <button onClick={() => handleFinalize(p.id, 'unfinalize')}
                                style={{ fontSize: 11, padding: '4px 9px', borderRadius: 6, border: 'none', background: '#fef3c7', color: '#b45309', cursor: 'pointer', fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4 }}>
                                <Unlock size={10} /> Unlock
                              </button>
                            )}
                          </div>
                        </td>
                      </> : <>
                        <td style={{ ...td, fontWeight: 600 }}>{new Date(p.year, p.month - 1).toLocaleString('default', { month: 'short', year: 'numeric' })}</td>
                        <td style={td}>{p.present_days}</td>
                        <td style={{ ...td, fontFamily: 'monospace', fontSize: 11 }}>{p.ot_hours}</td>
                        <td style={{ ...td, fontWeight: 600 }}>{fmt(p.gross)}</td>
                        <td style={{ ...td, color: '#dc2626' }}>{fmt(p.deductions)}</td>
                        <td style={{ ...td, fontWeight: 800, color: '#115e59' }}>{fmt(p.net_pay)}</td>
                        <td style={td}><span style={{ background: p.status === 'finalized' ? '#dcfce7' : '#fef3c7', color: p.status === 'finalized' ? '#15803d' : '#b45309', padding: '2px 8px', borderRadius: 6, fontSize: 11, fontWeight: 700 }}>{p.status}</span></td>
                        <td style={td}>
                          <button onClick={() => setViewSlip(p)} style={{ fontSize: 11, padding: '4px 10px', borderRadius: 6, border: 'none', background: '#eff6ff', color: '#1d4ed8', cursor: 'pointer', fontWeight: 700 }}>View</button>
                        </td>
                      </>}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* Approvals Table */}
      {tab === 'approvals' && (
        <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #e6e9ef', overflow: 'hidden' }}>
          <div style={{ padding: '12px 18px', borderBottom: '1px solid #e6e9ef', fontWeight: 700, fontSize: 14 }}>Pending Salary Approvals</div>
          {approvals.length === 0 ? (
            <div style={{ padding: 60, textAlign: 'center', color: '#94a3b8' }}>No pending approvals.</div>
          ) : (
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead><tr style={{ background: '#f8fafc' }}>
                {['Code', 'Name', 'Requested Basic', 'Requested On', 'Actions'].map(h => (
                  <th key={h} style={{ padding: '10px 14px', textAlign: 'left', fontSize: 11.5, fontWeight: 700, color: '#64748b', borderBottom: '1px solid #e6e9ef' }}>{h}</th>
                ))}
              </tr></thead>
              <tbody>
                {approvals.map((a, i) => (
                  <tr key={a.id} style={{ background: i % 2 === 0 ? '#fff' : '#fafafa' }}>
                    <td style={td}>{a.emp_code}</td>
                    <td style={{ ...td, fontWeight: 600 }}>{a.emp_name}</td>
                    <td style={{ ...td, fontWeight: 600 }}>{fmt(a.basic_salary)}</td>
                    <td style={td}>{new Date(a.created_at).toLocaleDateString('en-IN')}</td>
                    <td style={td}>
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button onClick={() => handleApprove(a.id, 'approve')} style={{ fontSize: 11, padding: '4px 10px', borderRadius: 6, border: 'none', background: '#16a34a', color: '#fff', cursor: 'pointer', fontWeight: 700 }}>Approve</button>
                        <button onClick={() => handleApprove(a.id, 'reject')} style={{ fontSize: 11, padding: '4px 10px', borderRadius: 6, border: 'none', background: '#dc2626', color: '#fff', cursor: 'pointer', fontWeight: 700 }}>Reject</button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {/* Modals */}
      {viewSlip && <PayslipModal slip={viewSlip} onClose={() => setViewSlip(null)} />}
      {editRow && <EditModal row={editRow} formula={formula} onClose={() => setEditRow(null)} onSaved={onSaved} />}
      {showFormulaSettings && <FormulaSettingsModal onClose={() => setShowFormulaSettings(false)} onSaved={loadFormula} />}
    </div>
  );
}

const navBtn = { width: 34, height: 34, borderRadius: 8, border: '1px solid #e6e9ef', background: '#fff', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' };
const td = { padding: '8px 12px', borderBottom: '1px solid #f1f5f9', fontSize: 13, whiteSpace: 'nowrap', verticalAlign: 'middle' };
const lbl = { fontSize: 12, fontWeight: 600, color: '#4b5566', display: 'block', marginBottom: 4 };
const inp = { width: '100%', height: 38, padding: '0 10px', border: '1.5px solid #e6e9ef', borderRadius: 8, fontSize: 13, outline: 'none', boxSizing: 'border-box' };
const btnOutline = { display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', borderRadius: 9, border: '1px solid #e6e9ef', background: '#fff', color: '#4b5566', cursor: 'pointer', fontSize: 13, fontWeight: 600 };
const btnPrimary = { display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', borderRadius: 9, border: 'none', background: '#115e59', color: '#fff', cursor: 'pointer', fontSize: 13, fontWeight: 700 };
